spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/test_banking
    username: banking
    password: banking
logging:
  level:
    root: INFO
